name: Build & Release VSIX

on:
  push:
    tags:
      - 'v*.*.*'     # v1.2.3 などのタグを push した時に実行
  workflow_dispatch:  # 手動実行も可

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck / Build (if you have)
        run: |
          if npm run | grep -q "compile"; then
            npm run compile
          fi

      - name: Package VSIX
        run: npx @vscode/vsce package
        # 出力: <name>-<version>.vsix （package.json に依存）

      - name: Upload VSIX as artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"

      - name: Create GitHub Release and upload VSIX
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
